name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'

      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: php artisan test

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Configura la conexión SSH y despliega el código
          ssh -o StrictHostKeyChecking=no user@your-vps-ip << 'EOF'
            cd /path/to/your/project
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
          EOF
